---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: apprcv
  name: apprcv
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: apprcv
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: apprcv
    spec:
      containers:
      - name: apprcv
        image: docker.io/ch4rls/apprcv
        imagePullPolicy: IfNotPresent
        env:
          - name: API_QUEUE
            value: "192.168.50.4"
        ports:
        - containerPort: 3020
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: apprcv
  name: apprcv
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3020
  selector:
    run: apprcv
  sessionAffinity: None
  type: LoadBalancer
