---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: appsend
  name: appsend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: appsend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: appsend
    spec:
      containers:
      - name: appsend
        image: docker.io/ch4rls/appsend
        imagePullPolicy: IfNotPresent
        env:
          - name: API_QUEUE
            value: "192.168.50.4"
        ports:
        - containerPort: 3010
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: appsend
  name: appsend
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3010
  selector:
    run: appsend
  sessionAffinity: None
  type: LoadBalancer
